"""audited_quality_resolution"""

import sqlalchemy as sa
from alembic import op

revision = "5a2fdefb3090"
down_revision = "826cbe2f4bb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quality_issues",
        sa.Column("resolution_state", sa.String(length=16), server_default="open", nullable=False),
    )
    op.add_column("quality_issues", sa.Column("resolution", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quality_issues", "resolution")
    op.drop_column("quality_issues", "resolution_state")
    # ### end Alembic commands ###
