"""initial_schema"""

import sqlalchemy as sa
from alembic import op

revision = "826cbe2f4bb6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("lottery", sa.String(length=8), nullable=False),
        sa.Column("dataset_kind", sa.String(length=12), nullable=False),
        sa.Column("draw_count", sa.Integer(), nullable=False),
        sa.Column("draws", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lottery", sa.String(length=8), nullable=False),
        sa.Column("dataset_kind", sa.String(length=12), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received", sa.Integer(), nullable=False),
        sa.Column("accepted", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("conflicts", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "draws",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lottery", sa.String(length=8), nullable=False),
        sa.Column("issue", sa.String(length=32), nullable=False),
        sa.Column("draw_date", sa.Date(), nullable=False),
        sa.Column("dataset_kind", sa.String(length=12), nullable=False),
        sa.Column("main_numbers", sa.JSON(), nullable=False),
        sa.Column("special_numbers", sa.JSON(), nullable=False),
        sa.Column("sales", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("pool_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("prizes", sa.JSON(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("ingestion_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(lottery = 'ssq' AND coalesce(json_array_length(main_numbers), -1) = 6 AND CAST(main_numbers ->> 0 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 1 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 0 AS INTEGER) < CAST(main_numbers ->> 1 AS INTEGER) AND CAST(main_numbers ->> 2 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 1 AS INTEGER) < CAST(main_numbers ->> 2 AS INTEGER) AND CAST(main_numbers ->> 3 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 2 AS INTEGER) < CAST(main_numbers ->> 3 AS INTEGER) AND CAST(main_numbers ->> 4 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 3 AS INTEGER) < CAST(main_numbers ->> 4 AS INTEGER) AND CAST(main_numbers ->> 5 AS INTEGER) BETWEEN 1 AND 33 AND CAST(main_numbers ->> 4 AS INTEGER) < CAST(main_numbers ->> 5 AS INTEGER) AND coalesce(json_array_length(special_numbers), -1) = 1 AND CAST(special_numbers ->> 0 AS INTEGER) BETWEEN 1 AND 16) OR (lottery = 'dlt' AND coalesce(json_array_length(main_numbers), -1) = 5 AND CAST(main_numbers ->> 0 AS INTEGER) BETWEEN 1 AND 35 AND CAST(main_numbers ->> 1 AS INTEGER) BETWEEN 1 AND 35 AND CAST(main_numbers ->> 0 AS INTEGER) < CAST(main_numbers ->> 1 AS INTEGER) AND CAST(main_numbers ->> 2 AS INTEGER) BETWEEN 1 AND 35 AND CAST(main_numbers ->> 1 AS INTEGER) < CAST(main_numbers ->> 2 AS INTEGER) AND CAST(main_numbers ->> 3 AS INTEGER) BETWEEN 1 AND 35 AND CAST(main_numbers ->> 2 AS INTEGER) < CAST(main_numbers ->> 3 AS INTEGER) AND CAST(main_numbers ->> 4 AS INTEGER) BETWEEN 1 AND 35 AND CAST(main_numbers ->> 3 AS INTEGER) < CAST(main_numbers ->> 4 AS INTEGER) AND coalesce(json_array_length(special_numbers), -1) = 2 AND CAST(special_numbers ->> 0 AS INTEGER) BETWEEN 1 AND 12 AND CAST(special_numbers ->> 1 AS INTEGER) BETWEEN 1 AND 12 AND CAST(special_numbers ->> 0 AS INTEGER) < CAST(special_numbers ->> 1 AS INTEGER))",
            name="ck_draw_numbers",
        ),
        sa.CheckConstraint("dataset_kind IN ('real', 'synthetic')", name="ck_draw_kind"),
        sa.CheckConstraint("pool_amount IS NULL OR pool_amount >= 0", name="ck_draw_pool"),
        sa.CheckConstraint("sales IS NULL OR sales >= 0", name="ck_draw_sales"),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lottery", "issue", name="uq_draw_lottery_issue"),
    )
    op.create_index(
        "ix_draw_scope_date", "draws", ["lottery", "dataset_kind", "draw_date", "issue"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("lottery", sa.String(length=8), nullable=False),
        sa.Column("dataset_kind", sa.String(length=12), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("dataset_id", sa.String(length=64), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued','running','completed','failed','cancelled')", name="ck_job_status"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_claim", "jobs", ["status", "created_at"], unique=False)
    op.create_table(
        "quality_issues",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ingestion_id", sa.String(length=36), nullable=False),
        sa.Column("lottery", sa.String(length=8), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("issue", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("raw_record", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quality_issues_ingestion_id"), "quality_issues", ["ingestion_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quality_issues_ingestion_id"), table_name="quality_issues")
    op.drop_table("quality_issues")
    op.drop_index("ix_job_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_draw_scope_date", table_name="draws")
    op.drop_table("draws")
    op.drop_table("ingestion_runs")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###
